In [2]:
import requests
import pandas as pd
import time

In [3]:
API_KEY="AIzaSyDWqZqIEJimSaY2P7aKt1f85NrDL-STR-s"

In [4]:
queries = [
    "fiction",
    "non fiction",
    "science",
    "history",
    "technology",
    "programming",
    "business",
    "romance",
    "mystery",
    "fantasy",
    "psychology",
    "medical",
    "self help",
    "biography",
    "philosophy",
    "economics",
    "politics",
    "sociology",
    "geography",
    "art and design",
    "english literature",
    "religion",
    "motivational books",

    "computer science books",
    "data structures and algorithms",
    "python programming",
    "java programming",
    "machine learning books",
    "artificial intelligence books",
    "web development books",

    "engineering mathematics",
    "electrical engineering books",
    "mechanical engineering books",
    "civil engineering books",
    "electronics engineering books",

    "neet biology",
    "neet physics",
    "neet chemistry",
    "medical textbooks",
    "human anatomy books",
    "pharmacology basics",

    "jee mains physics",
    "jee advanced physics",
    "jee chemistry problems",
    "jee mathematics",

    "upsc civil services",
    "upsc gs paper 1",
    "upsc history books",
    "upsc polity books",
    "upsc geography books",
    "indian economy upsc",
    "current affairs books",

    "ssc cgl books",
    "ssc reasoning",
    "ssc maths books",
    "ssc general awareness",

    "ca foundation accounting",
    "ca inter taxation",
    "ca study material",
    "commerce books",
    "financial accounting books",

    "aptitude reasoning books",
    "quantitative aptitude",
    "logical reasoning",
    "general knowledge india",

    "school textbooks",
    "cbse books",
    "ncert books",
    "high school mathematics",
    "high school science"
]

In [ ]:
books = []

for q in queries:

    for start in range(0, 250, 40):

        url = f"https://www.googleapis.com/books/v1/volumes?q={q}&maxResults=40&startIndex={start}&key={API_KEY}"

        response = requests.get(url)

        if response.status_code == 200:

            data = response.json()

            if "items" in data:

                for item in data["items"]:

                    info = item.get("volumeInfo", {})

                    books.append({
                        "title": info.get("title", ""),
                        "description": info.get("description", ""),
                        "authors": info.get("authors", []),
                        "categories": info.get("categories", [])
                    })

In [76]:
df = pd.DataFrame(books)

print("Total Movies:", len(df))
print(df.head())

Total Movies: 0
Empty DataFrame
Columns: []
Index: []

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        5020 non-null   object
 1   description  5020 non-null   object
 2   authors      5020 non-null   object
 3   categories   5020 non-null   object
dtypes: object(4)
memory usage: 157.0+ KB

In [46]:
df.isnull().sum()

title          0
description    0
authors        0
categories     0
dtype: int64

In [47]:
df.to_csv("books_data.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [6]:
import pandas as pd

df = pd.read_csv("books_data.csv")

df.head()

,title,description,authors,categories
0,Library of Congress Subject Headings,NaN,['Library of Congress'],"['Subject headings, Library of Congress']"
1,Library of Congress Subject Headings,NaN,['Library of Congress. Cataloging Policy and S...,"['Subject headings, Library of Congress']"
2,The Royal Magazine,NaN,[],[]
3,Pearson's Magazine,NaN,[],['English fiction']
4,Catalogue of the Oakland Free Public Library,NaN,['Oakland Free Library'],['Library catalogs']

In [7]:
df.isnull().sum()

title             0
description    3310
authors           0
categories        0
dtype: int64

In [8]:
df["description"] = df["description"].fillna("")
df["categories"] = df["categories"].fillna("")

In [9]:
df.isnull().sum()

title          0
description    0
authors        0
categories     0
dtype: int64

In [10]:
df["content"] = (
    df["description"] + " " +
    df["categories"]
)

In [11]:
df["content"] = df["content"].str.lower()

In [12]:
df.tail()

,title,description,authors,categories,content
5015,Summarized Proceedings of the American Associa...,,['American Association for the Advancement of ...,['Science'],['science']
5016,Engineered Materials Abstracts,,[],['Ceramic materials'],['ceramic materials']
5017,SPIE ... Directory for Members,,['Society of Photo-Optical Instrumentation Eng...,['Engineers'],['engineers']
5018,The Electrical Engineer,,[],['Electrical engineering'],['electrical engineering']
5019,Disha 15 Mock Test Series NTA JEE Main 2026 wi...,The updated 5th edition of Disha’s 15 Mock Tes...,['Disha Experts'],['Antiques & Collectibles'],the updated 5th edition of disha’s 15 mock tes...

In [13]:
import re
def remove_html(text):
    return re.sub(r'<.*?>','',str(text))

In [14]:
df['content']=df['content'].apply(remove_html)

In [15]:
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

df["content"] = df["content"].apply(remove_url)

In [16]:
import string

def remove_punctuation(text):
    return text.translate(
        str.maketrans('', '', string.punctuation)
    )

df["content"] = df["content"].apply(remove_punctuation)

In [17]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

df["content"] = df["content"].apply(remove_numbers)

In [18]:
def remove_spaces(text):
    return re.sub(r'\s+', ' ', text).strip()

df["content"] = df["content"].apply(remove_spaces)

In [19]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [20]:
from nltk.tokenize import word_tokenize
df["tokens"]=df["content"].apply(word_tokenize)

In [ ]:
from nltk.corpus import stopwords

nltk.download('stopw5ords')

stop_words = set(stopwords.words('english'))

df["tokens"] = df["tokens"].apply(
    lambda words: [
        word for word in words
        if word not in stop_words
    ]
)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [22]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in C:\Users\LENOVO\anaconda3\Lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from spacy) (0.17.4)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (2.4.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (81.0.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in C:\Users\LENOVO\anaconda3\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.12.1)
Requirement already satisfied: httpcore==1.* in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in C:\Users\LENOVO\anaconda3\Lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python313\site-packages (from jinja2->spacy) (3.0.2)
Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 1.4 MB/s eta 0:00:09
     -- ------------------------------------- 0.8/12.8 MB 1.5 MB/s eta 0:00:08
     --- ------------------------------------ 1.0/12.8 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/12.8 MB 1.3 MB/s eta 0:00:09
     ---- ----------------------------------- 1.6/12.8 MB 1.4 MB/s eta 0:00:09
     ----- ---------------------------------- 1.8/12.8 MB 1.4 MB/s eta 0:00:09
     ------ --------------------------------- 2.1/12.8 MB 1.3 MB/s eta 0:00:08
     ------- -------------------------------- 2.4/12.8 MB 1.3 MB/s eta 0:00:08
     -------- ------------------------------- 2.6/12.8 MB 1.3 MB/s eta 0:00:08
     --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:08
     --------- ------------------------------ 3.1/12.8 MB 1.3 MB/s eta 0:00:08
     ---------- ----------------------------- 3.4/12.8 MB 1.3 MB/s eta 0:00:08
     ---------- ----------------------------- 3.4/12.8 MB 1.3 MB/s eta 0:00:08
     ----------- ---------------------------- 3.7/12.8 MB 1.2 MB/s eta 0:00:08
     ------------ --------------------------- 3.9/12.8 MB 1.2 MB/s eta 0:00:08
     ------------- -------------------------- 4.2/12.8 MB 1.2 MB/s eta 0:00:08
     ------------- -------------------------- 4.2/12.8 MB 1.2 MB/s eta 0:00:08
     ------------- -------------------------- 4.5/12.8 MB 1.1 MB/s eta 0:00:08
     -------------- ------------------------- 4.7/12.8 MB 1.1 MB/s eta 0:00:08
     -------------- ------------------------- 4.7/12.8 MB 1.1 MB/s eta 0:00:08
     --------------- ------------------------ 5.0/12.8 MB 1.1 MB/s eta 0:00:08
     ---------------- ----------------------- 5.2/12.8 MB 1.1 MB/s eta 0:00:07
     ----------------- ---------------------- 5.5/12.8 MB 1.1 MB/s eta 0:00:07
     ------------------ --------------------- 5.8/12.8 MB 1.1 MB/s eta 0:00:07
     ------------------ --------------------- 6.0/12.8 MB 1.1 MB/s eta 0:00:07
     -------------------- ------------------- 6.6/12.8 MB 1.1 MB/s eta 0:00:06
     -------------------- ------------------- 6.6/12.8 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.8/12.8 MB 1.1 MB/s eta 0:00:06
     --------------------- ------------------ 6.8/12.8 MB 1.1 MB/s eta 0:00:06
     ---------------------- ----------------- 7.1/12.8 MB 1.1 MB/s eta 0:00:06
     ---------------------- ----------------- 7.3/12.8 MB 1.1 MB/s eta 0:00:06
     ---------------------- ----------------- 7.3/12.8 MB 1.1 MB/s eta 0:00:06
     ----------------------- ---------------- 7.6/12.8 MB 1.1 MB/s eta 0:00:05
     ------------------------ --------------- 7.9/12.8 MB 1.1 MB/s eta 0:00:05
     ------------------------- -------------- 8.1/12.8 MB 1.1 MB/s eta 0:00:05
     ------------------------- -------------- 8.1/12.8 MB 1.1 MB/s eta 0:00:05
     -------------------------- ------------- 8.4/12.8 MB 1.1 MB/s eta 0:00:05
     --------------------------- ------------ 8.9/12.8 MB 1.1 MB/s eta 0:00:04
     ---------------------------- ----------- 9.2/12.8 MB 1.1 MB/s eta 0:00:04
     ---------------------------- ----------- 9.2/12.8 MB 1.1 MB/s eta 0:00:04
     ----------------------------- ---------- 9.4/12.8 MB 1.1 MB/s eta 0:00:04
     ------------------------------ --------- 9.7/12.8 MB 1.1 MB/s eta 0:00:03
     ------------------------------ --------- 9.7/12.8 MB 1.1 MB/s eta 0:00:03
     ------------------------------- -------- 10.0/12.8 MB 1.0 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.8 MB 1.0 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.8 MB 1.0 MB/s eta 0:00:03
     ------------------------------- -------- 10.2/12.8 MB 1.0 MB/s eta 0:00:03
     -------------------------------- ------- 10.5/12.8 MB 1.0 MB/s eta 0:00:03
     -------------------------------- ------- 10.5/12.8 MB 1.0 MB/s eta 0:00:03
     ------------------------------- ------ 10.7/12.8 MB 987.8 kB/s eta 0:00:03
     ------------------------------- ------ 10.7/12.8 MB 987.8 kB/s eta 0:00:03
     ------------------------------- ------ 10.7/12.8 MB 987.8 kB/s eta 0:00:03
     -------------------------------- ----- 11.0/12.8 MB 953.7 kB/s eta 0:00:02
     --------------------------------- ---- 11.3/12.8 MB 951.5 kB/s eta 0:00:02
     --------------------------------- ---- 11.3/12.8 MB 951.5 kB/s eta 0:00:02
     ---------------------------------- --- 11.5/12.8 MB 943.7 kB/s eta 0:00:02
     ----------------------------------- -- 11.8/12.8 MB 946.7 kB/s eta 0:00:02
     ----------------------------------- -- 11.8/12.8 MB 946.7 kB/s eta 0:00:02
     ----------------------------------- -- 12.1/12.8 MB 942.5 kB/s eta 0:00:01
     ------------------------------------ - 12.3/12.8 MB 938.6 kB/s eta 0:00:01
     ------------------------------------ - 12.3/12.8 MB 938.6 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 927.9 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 927.9 kB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 921.8 kB/s  0:00:13
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [23]:
import spacy

nlp = spacy.load("en_core_web_sm")

def lemmatize(tokens):

    doc = nlp(" ".join(tokens))

    return [
        token.lemma_
        for token in doc
    ]

df["tokens"] = df["tokens"].apply(lemmatize)

In [24]:
df["processed_text"] = df["tokens"].apply(
    lambda x: " ".join(x)
)

In [25]:
df.head()

,title,description,authors,categories,content,tokens,processed_text
0,Library of Congress Subject Headings,,['Library of Congress'],"['Subject headings, Library of Congress']",subject headings library of congress,"[subject, heading, library, congress]",subject heading library congress
1,Library of Congress Subject Headings,,['Library of Congress. Cataloging Policy and S...,"['Subject headings, Library of Congress']",subject headings library of congress,"[subject, heading, library, congress]",subject heading library congress
2,The Royal Magazine,,[],[],,[],
3,Pearson's Magazine,,[],['English fiction'],english fiction,"[english, fiction]",english fiction
4,Catalogue of the Oakland Free Public Library,,['Oakland Free Library'],['Library catalogs'],library catalogs,"[library, catalog]",library catalog

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

tfidf_matrix = tfidf.fit_transform(
    df["processed_text"]
)

In [27]:
tfidf_matrix.shape

(5020, 14173)

In [28]:
import re
import string

def preprocess_query(text):

    text = str(text).lower()

    text = re.sub(r'<.*?>', '', text)

    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    text = re.sub(r'\d+', '', text)

    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [29]:
import pickle

In [30]:
with open("tfidf.pkl", "wb") as f:
    pickle.dump(tfidf, f)
with open("tfidf_matrix.pkl", "wb") as f:
    pickle.dump(tfidf_matrix, f)